[Tutorial/router] Make react-navigation drawer docs
JeffGuKang/react-native-tutorial pull request #127
Opened 2019-10-15 04:42 UTC by sdalbsoo

issue: #57 

## Changes

Add navigation drawer docs(kr).

## How Verified

N/A

### Notes

N/A

### References

[react navigation](https://reactnavigation.org/docs/en/drawer-based-navigation.html)
[convert mp4(mov) to gif](https://ezgif.com/video-to-gif)

2019-10-15 11:44 UTC, JeffGuKang commented
@samslow How about review this?

2019-10-16 03:09 UTC, samslow requested changes

2019-10-16 03:09 UTC, samslow commented on docs/router-tutorial/03-react-navigation-drawer/04-drawer-config/drawer-navi-component-config-kr.md
> +이외에도 더 많은 **DrawerNavigatorConfig** 가 있으니 [여기 사이트](https://reactnavigation.org/docs/en/drawer-navigator.html#drawernavigatorconfig)에 들어가서 참고하길 바란다.
`여기 사이트` 보다는 `여기` 나 `사이트` 같은 표현으로 문맥이 자연스러우면 좋을 것 같습니다.

2019-10-16 11:28 UTC, beeeg55 submitted a review, later dismissed

2019-10-19 10:26 UTC, JeffGuKang approved these changes

2019-10-19 10:26 UTC, merged