Translate documents in Korean (01,02,03,04) #138
JeffGuKang/react-native-tutorial pull request #146
Opened 2019-10-17 06:47 UTC by sonypark

resolve #138 

## Fix
- Add missing image on a post
- Add Github source link

## Changes
- Create tutorial documents in Korean
- 01 getting-started-kr.md
- 02 change-background-and-title-kr.md
- 03 cardview-kr.md
- 04 scrollview-kr.md

## How Verified
#### (Automated Tests)
- N/A

#### (Manual Tests)
- Test in local with jekyll

### Notes
- Request review on this PR to @Haerang94

### References
- https://facebook.github.io/react-native/docs/getting-started

2019-10-17 12:52 UTC, qkreltms requested changes

2019-10-17 12:52 UTC, qkreltms commented on docs/basic-tutorial/basic-features(todolist)/01-getting-started/getting-started-kr.md
> +환경 설정을 모두 마치셨으면, React Native CLI 명령어로 React Native 프로젝트를 만들어보겠습니다.
"환경 설정을 모두 완료했다면, "이 더 어울릴것 같습니다.

2019-10-17 12:52 UTC, qkreltms commented on docs/basic-tutorial/basic-features(todolist)/01-getting-started/getting-started-kr.md
> +React Native 애플리케이션을 만드는 방법으로는 Expo 또는 React Native CLI를 사용할 수 있습니다. Expo를 사용하면 쉽게 프로젝트를 설치하고 실행할 수 있는 장점이 있지만 개발 환경이 Expo에서 제공하는 기능에 한정되어 Native 환경을 모두 이용할 수는 없다는 단점이 있습니다. React Native CLI를 이용하면 설치
간결하게 "본 튜토리얼에서는 React Native CLI를 이용해 진행하겠습니다" 만 적어도 괜찮을 것 같습니다.

2019-10-17 13:10 UTC, JeffGuKang commented on docs/basic-tutorial/basic-features(todolist)/01-getting-started/getting-started-kr.md
> +React Native 애플리케이션을 만드는 방법으로는 Expo 또는 React Native CLI를 사용할 수 있습니다. Expo를 사용하면 쉽게 프로젝트를 설치하고 실행할 수 있는 장점이 있지만 개발 환경이 Expo에서 제공하는 기능에 한정되어 Native 환경을 모두 이용할 수는 없다는 단점이 있습니다. React Native CLI를 이용하면 설치
I think this is OK.

2019-10-17 13:11 UTC, JeffGuKang commented on docs/basic-tutorial/basic-features(todolist)/01-getting-started/getting-started-kr.md
> +환경 설정을 모두 마치셨으면, React Native CLI 명령어로 React Native 프로젝트를 만들어보겠습니다.
> 
> 
> "환경 설정을 모두 완료했다면, " This one would be better for me.

I agree with this

2019-10-17 14:09 UTC, sonypark commented on docs/basic-tutorial/basic-features(todolist)/01-getting-started/getting-started-kr.md
> +환경 설정을 모두 마치셨으면, React Native CLI 명령어로 React Native 프로젝트를 만들어보겠습니다.
That's right, Thanks for your suggestion.

2019-10-18 12:23 UTC, JeffGuKang approved these changes

2019-10-18 12:23 UTC, merged