Typo correction and fixed  jekyll Form
JeffGuKang/react-native-tutorial pull request #170
Opened 2019-10-19 05:06 UTC by Haerang94

## Fix #
-  Fixed  jekyll form

## Changes
- Fixed some contents according to  jekyll form 
- Typo correction 

## How Verified
#### (Automated Tests)
- N/A
#### (Manual Tests)
- N/A

### Notes
- It can be updated.

### References
- N/A

2019-10-19 10:33 UTC, JeffGuKang requested changes

2019-10-19 10:33 UTC, JeffGuKang commented on docs/basic-tutorial/basic-functions/02-debugging/debugging-kr.md
> +title: 2.
There is no title.

2019-10-19 15:45 UTC, sonypark commented on docs/basic-tutorial/basic-functions/02-debugging/debugging-kr.md
> +title: 2.
I found some awkward sentences in this file.

- 최신의 JSContext를 **수동적으로 선택하지 않아도 된다.** => "수동으로 선택하지 않아도 된다."
- `console.error()`를 사용해서 **수동적으로 생기게 할 수 있다.** => "생기게 할 수 있다."
- 특정 경고표시들은 다음과 같이 프로그램적으로 **무시시킬 수 있다.** => "무시할 수 있다"
- 옐로우 박스는 IS_TESTING 환경 변수를 설정해서 **설정해제 시킬 수 있다.** => "설정해제 할 수 있다"
- 레드박스와 옐로우 박스는 릴리즈 빌드 버전에서는 자동적으로 **무시시킬 수 있다.**  => "무시할 수 있다."

It would be better if you edit the sentences to more natural flow in Korean.

2019-10-21 06:15 UTC, Haerang94 commented
@JeffGuKang  @sonypark  Can you review this file again please?

2019-10-21 06:45 UTC, JeffGuKang approved these changes
Good Korean title.

2019-10-21 06:46 UTC, merged