Init debugging document
JeffGuKang/react-native-tutorial pull request #25
Opened 2019-09-16 13:21 UTC by Duckuism

## Fix
- Need directories to manage sources and docs about Debugging
## Changes
- Add directories about Debugging
- Add images to be needed in documents
## How Verified
- N/A
## Notes
- N/A

2019-09-16 13:45 UTC, JeffGuKang requested changes
Thank you for PR. 

There are some mistakes. :)

## Do not use space to file name when you create. 
For example, 
`iOS Debugging.md` => `iOS-Debugging.md` 

if you use some command on shell as `git rm iOS-Debugging.md`, spaces can make confusing as `git rm iOS\ Debugging.md`

## Begin all subject lines with a capital letter

`add translated documents about Debugging` => `Add ...`

I will wait next commits for merging.

2019-09-16 23:36 UTC, Duckuism commented
@JeffGuKang Thank you for your kindly reviews. I've just applied your reviews 🙂

2019-09-17 00:00 UTC, JeffGuKang approved these changes

2019-09-17 00:00 UTC, JeffGuKang approved these changes

2019-09-17 00:00 UTC, merged

2019-09-17 00:03 UTC, JeffGuKang commented
Awesome 👍