Add translated docs(1~3) for iOS-Debugging.md
JeffGuKang/react-native-tutorial pull request #26
Opened 2019-09-17 02:25 UTC by alledy

Add translated contents in Korean for iOS-Debugging.md

There are subheads(h3 heading) in the first subject(`Using the Debugger`) but I haven't numbered. 
If it needed I'll fix. Thanks.

2019-09-17 02:31 UTC, JeffGuKang approved these changes

2019-09-17 18:45 UTC, Duckuism requested changes
Great job! 👍🏻 Please leave your answer to my reviews.

2019-09-17 18:45 UTC, Duckuism commented on docs/Debugging/iOS-Debugging.md
> +![](https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/Art/XC_O_DebugFeatures_2x.png)
You are using hyperlinks of developert.apple.com. In this case, If the paths of links are changed, all images will be disappeared in our markdown files. I have made the Image directory in docs/Debugging. You should add the image files in the Image directory and change the paths of image sources just like `./Images/<:image source name>` after download the image sources.

EX) `![](./Images/instruments_window_2x-99f5e667-de70-44c2-96f1-800b8543bc42.png)`

2019-09-17 18:45 UTC, Duckuism commented on docs/Debugging/iOS-Debugging.md
> +워크스페이스의 툴바에서 실행 버튼을 누르면 당신의 앱은 성공적으로 빌드될 것입니다. Xcode는 당신의 앱을 실행시키고 디버깅 세션을 시작합니다. `data tips` 같은 그래픽 툴이나 [Quick Look](<https://developer.apple.com/library/archive/documentation/DeveloperTools/Concept
As you can often see in translation, it would seem natural in context to delete `당신의` or `너의` or `네가`.

2019-09-18 00:38 UTC, alledy commented on docs/Debugging/iOS-Debugging.md
> +![](https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/Art/XC_O_DebugFeatures_2x.png)
I didn't notice that point. I'll change. Thanks!

2019-09-18 06:38 UTC, JeffGuKang commented
Good job. But work with new branch always even update code in your repository.
Updating the master branch directly can be confusing.

2019-09-18 06:55 UTC, Duckuism commented
Refer to this screenshot.
![스크린샷 2019-09-18 15 54 30](https://user-images.githubusercontent.com/24688568/65122756-b2853000-da2c-11e9-8906-77b8a15fd3ad.png)

2019-09-19 11:29 UTC, closed without merging