Add basic example for ios
JeffGuKang/react-native-tutorial pull request #53
Opened 2019-09-24 13:14 UTC by alledy

## Fix #
- Need to add a new basic example for ios

## Changes
- Made a new example named ClickThePaintings in Examples/Debugging
- Installed babel-plugin-module-resolver and add alias(`@: ./src`) in babel.config.js file
- Installed react-router-native for routing
- Implemented a function where click a painting and get brief information

## How Verified
N/A

### Notes
N/A

### References
N/A

2019-09-26 23:01 UTC, JeffGuKang commented
Good. Do not forget to use capital letter for first character of the commit message.

2019-09-26 23:02 UTC, JeffGuKang requested changes
Good! Do not forget to use capital letter for first character of the commit message.

2019-09-28 15:05 UTC, Duckuism approved these changes
I was impressed with the good use of `react-router-native`

2019-09-28 15:05 UTC, Duckuism commented on Examples/Debugging/ClickThePaintings/.gitignore
> +!default.pbxuser
Why are you using this logical operator in here? Wanna know your intention.

2019-09-28 15:05 UTC, Duckuism commented on Examples/Debugging/ClickThePaintings/src/App.js
> +import TopBar from '@/components/TopBar';
Thanks to you, I know something [new](https://stackoverflow.com/a/42753045)!

2019-09-28 16:59 UTC, JeffGuKang commented
@alledy How about resolve requested changes?

2019-09-29 05:38 UTC, Duckuism commented
@JeffGuKang She is traveling until next Wednesday. I think it will be resolved after next Wednesday. 😀

2019-10-02 01:15 UTC, merged